kind: pipeline
name: default
type: docker

steps:
  - name: pull
    image: python:3.9
  - name: push-dev
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.hub.docker.com
      repo: registry.hub.docker.com/tyleragostino/spinnyboi
      tags: dev
      build_args: BUILDKIT_INLINE_CACHE=1
    when:
      branch:
        - dev
  - name: push-main
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.hub.docker.com
      repo: registry.hub.docker.com/tyleragostino/spinnyboi
      tags: latest
      build_args: BUILDKIT_INLINE_CACHE=1
    when:
      branch:
        - main
trigger:
  ref:
    - refs/heads/main
    - refs/heads/dev
