kind: pipeline
name: default
type: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: hub.docker.com
      username: tyleragostino
      password: ${DOCKER_PASSWORD}
      repo: tyleragostino/spinnyboi
      tags: latest

trigger:
  ref:
    - refs/heads/main