# Define profiles here, which can be used by typing `/spin [profile_name]`
# A template below
#
# profile_name:
#   tracks:
#     - track_name: track_weight
#     ...
#   cars:
#     - car_name: car_weight
#     ...
season4:
  tracks: # Fair share weight = 24            # Max grid spots
    - Charlotte Roval: 8                                # 60
    - Charlotte Roval 2018: 8
    - Charlotte Roval Long 2018: 8

#    - Lime Rock GP: 6                         # 60
#    - Lime Rock Classic: 6
#    - Lime Rock Chicanes: 6
#    - Lime Rock West Bend: 6

    - Okayama Full: 12                        # 62
    - Okayama Short: 12

    - Oran GP: 8                              # 57
    - Oran Moto: 8
    - Oran South: 8

#    - Oulton Intl: 3                          # 40
#    - Oulton Fosters: 3
#    - Oulton Island: 3
#    - Oulton Intl no Hislop: 3
#    - Oulton Intl no Brittens: 3
#    - Oulton Intl no Chicanes: 3
#    - Oulton Fosters w Hislop: 3
#    - Oulton Historic: 3

    - Rudskogen Motorsenter: 24               # 60

#    - Summit Point Regular: 12                # 58
#    - Summit Point Short: 12

#    - Tsukuba 2k Full: 8                      # 60
#    - Tsukuba 2k Moto: 8
#    - Tsukuba 2k Short: 8

    - VIR Full: 6                             # 60
    - VIR South: 6
    - VIR North: 6
    - VIR Grand: 6

    - Laguna Seca: 24                         # 62

#    - Watkins Glen Cup: 6                     # 60
#    - Watkins Glen Boot: 6
#    - Watkins Glen Classic Boot: 6
#    - Watkins Glen Classic: 6
#
#    - Sonoma Cup: 12                          # 62
#    - Sonoma Cup Historic: 12

    - Daytona Road: 10       # target 80%    # 60
    - Daytona NASCAR Road: 9                 # 60
#    - Daytona Short: 4                        # 42
#    - Daytona Road 2008: 4                    # 43
#    - Daytona Short 2008: 4                   # 28
#    - Daytona Moto 2008: 4                    # 43

    - Mid-Ohio Full: 6       # target 80%     # 62
    - Mid-Ohio Chicane: 6
    - Mid-Ohio Short: 6

    - Road Atlanta Full: 6    # target 80%    # 62
    - Road Atlanta Short: 6
    - Road Atlanta Club: 6

    - Mount Panorama: 19   # target 80%       # 62

    - Montreal: 19       # target 80%         # 62

    - Phoenix Road: 19   # target 80%         # 51
conditions:
  starttime:
    #    - MIDNIGHT - 1x Time Acceleration: 3    # 1 AM, 100% dark
    #    - 1 AM - 1x Time Acceleration: 3    # 2 AM, 100% dark
    #    - 2 AM - 1x Time Acceleration: 3    # 3 AM, 100% dark
    #    - 3 AM - 1x Time Acceleration: 3    # 4 AM, 100% dark
    #    - 4 AM - 1x Time Acceleration: 3    # 5 AM, 100% dark
    #    - 5 AM - 1x Time Acceleration: 3    # 6 AM, 100% dark
    #    - 6 AM - 1x Time Acceleration: 3    # 7 AM, 100% dark
    - 7 AM - 1x Time Acceleration: 1    # 8 AM, 0% dark
    - 8 AM - 1x Time Acceleration: 1    # 9 AM, 0% dark
    - 9 AM - 1x Time Acceleration: 1    # 10 AM, 0% dark
    - 10 AM - 1x Time Acceleration: 1    # 11 AM, 0% dark
    - 11 AM - 1x Time Acceleration: 1    # 12 PM, 0% dark
    - NOON - 1x Time Acceleration: 1    # 1 PM, 0% dark
    - 1 PM - 1x Time Acceleration: 1    # 2 PM, 0% dark
    - 2 PM - 1x Time Acceleration: 1    # 3 PM, 0% dark
    - 3 PM - 1x Time Acceleration: 1    # 4 PM, 0% dark
    - 4 PM - 1x Time Acceleration: 1    # 5 PM, 0% dark
    - 5 PM - 1x Time Acceleration: 1    # 6 PM, 0% dark
    - 6 PM - 1x Time Acceleration: 1    # 7 PM, 0% dark
    #    - 7 PM - 1x Time Acceleration: 3    # 8 PM, 100% dark
    #    - 8 PM - 1x Time Acceleration: 3    # 9 PM, 100% dark
    #    - 9 PM - 1x Time Acceleration: 3    # 10 PM, 100% dark
    #    - 10 PM - 1x Time Acceleration: 3    # 11 PM, 100% dark
    #    - 11 PM - 1x Time Acceleration: 3    # 12 AM, 100% dark
    #    - MIDNIGHT - 2x Time Acceleration: 3    # 2 AM, 100% dark
    #    - 1 AM - 2x Time Acceleration: 3    # 3 AM, 100% dark
    #    - 2 AM - 2x Time Acceleration: 3    # 4 AM, 100% dark
    #    - 3 AM - 2x Time Acceleration: 3    # 5 AM, 100% dark
    #    - 4 AM - 2x Time Acceleration: 3    # 6 AM, 100% dark
    #    - 5 AM - 2x Time Acceleration: 3    # 7 AM, 100% dark
    #    - 6 AM - 2x Time Acceleration: 3    # 8 AM, 50% dark
    - 7 AM - 2x Time Acceleration: 1    # 9 AM, 0% dark
    - 8 AM - 2x Time Acceleration: 1    # 10 AM, 0% dark
    - 9 AM - 2x Time Acceleration: 1    # 11 AM, 0% dark
    - 10 AM - 2x Time Acceleration: 1    # 12 PM, 0% dark
    - 11 AM - 2x Time Acceleration: 1    # 1 PM, 0% dark
    - NOON - 2x Time Acceleration: 1    # 2 PM, 0% dark
    - 1 PM - 2x Time Acceleration: 1    # 3 PM, 0% dark
    - 2 PM - 2x Time Acceleration: 1    # 4 PM, 0% dark
    - 3 PM - 2x Time Acceleration: 1    # 5 PM, 0% dark
    - 4 PM - 2x Time Acceleration: 1    # 6 PM, 0% dark
    - 5 PM - 2x Time Acceleration: 1    # 7 PM, 0% dark
    #    - 6 PM - 2x Time Acceleration: 3    # 8 PM, 50% dark
    #    - 7 PM - 2x Time Acceleration: 3    # 9 PM, 100% dark
    #    - 8 PM - 2x Time Acceleration: 3    # 10 PM, 100% dark
    #    - 9 PM - 2x Time Acceleration: 3    # 11 PM, 100% dark
    #    - 10 PM - 2x Time Acceleration: 3    # 12 AM, 100% dark
    #    - 11 PM - 2x Time Acceleration: 3    # 1 AM, 100% dark
    #    - MIDNIGHT - 4x Time Acceleration: 3    # 4 AM, 100% dark
    #    - 1 AM - 4x Time Acceleration: 3    # 5 AM, 100% dark
    #    - 2 AM - 4x Time Acceleration: 3    # 6 AM, 100% dark
    #    - 3 AM - 4x Time Acceleration: 3    # 7 AM, 100% dark
    #    - 4 AM - 4x Time Acceleration: 3    # 8 AM, 75% dark
    #    - 5 AM - 4x Time Acceleration: 3    # 9 AM, 50% dark
    - 6 AM - 4x Time Acceleration: 3    # 10 AM, 25% dark
    - 7 AM - 4x Time Acceleration: 1    # 11 AM, 0% dark
    - 8 AM - 4x Time Acceleration: 1    # 12 PM, 0% dark
    - 9 AM - 4x Time Acceleration: 1    # 1 PM, 0% dark
    - 10 AM - 4x Time Acceleration: 1    # 2 PM, 0% dark
    - 11 AM - 4x Time Acceleration: 1    # 3 PM, 0% dark
    - NOON - 4x Time Acceleration: 1    # 4 PM, 0% dark
    - 1 PM - 4x Time Acceleration: 1    # 5 PM, 0% dark
    - 2 PM - 4x Time Acceleration: 1    # 6 PM, 0% dark
    - 3 PM - 4x Time Acceleration: 1    # 7 PM, 0% dark
    - 4 PM - 4x Time Acceleration: 3    # 8 PM, 25% dark
    #    - 5 PM - 4x Time Acceleration: 3    # 9 PM, 50% dark
    #    - 6 PM - 4x Time Acceleration: 3    # 10 PM, 75% dark
    #    - 7 PM - 4x Time Acceleration: 3    # 11 PM, 100% dark
    #    - 8 PM - 4x Time Acceleration: 3    # 12 AM, 100% dark
    #    - 9 PM - 4x Time Acceleration: 3    # 1 AM, 100% dark
    #    - 10 PM - 4x Time Acceleration: 3    # 2 AM, 100% dark
    #    - 11 PM - 4x Time Acceleration: 3    # 3 AM, 100% dark
    #    - MIDNIGHT - 8x Time Acceleration: 3    # 8 AM, 88% dark
    #    - 1 AM - 8x Time Acceleration: 3    # 9 AM, 75% dark
    #    - 2 AM - 8x Time Acceleration: 3    # 10 AM, 63% dark
    #    - 3 AM - 8x Time Acceleration: 3    # 11 AM, 50% dark
    #    - 4 AM - 8x Time Acceleration: 3    # 12 PM, 37% dark
    - 5 AM - 8x Time Acceleration: 3    # 1 PM, 25% dark
    - 6 AM - 8x Time Acceleration: 3    # 2 PM, 13% dark
    - 7 AM - 8x Time Acceleration: 1    # 3 PM, 0% dark
    - 8 AM - 8x Time Acceleration: 1    # 4 PM, 0% dark
    - 9 AM - 8x Time Acceleration: 1    # 5 PM, 0% dark
    - 10 AM - 8x Time Acceleration: 1    # 6 PM, 0% dark
    - 11 AM - 8x Time Acceleration: 1    # 7 PM, 0% dark
    - NOON - 8x Time Acceleration: 3    # 8 PM, 13% dark
    - 1 PM - 8x Time Acceleration: 3    # 9 PM, 25% dark
#    - 2 PM - 8x Time Acceleration: 3    # 10 PM, 37% dark
#    - 3 PM - 8x Time Acceleration: 3    # 11 PM, 50% dark
#    - 4 PM - 8x Time Acceleration: 3    # 12 AM, 63% dark
#    - 5 PM - 8x Time Acceleration: 3    # 1 AM, 75% dark
#    - 6 PM - 8x Time Acceleration: 3    # 2 AM, 88% dark
#    - 7 PM - 8x Time Acceleration: 3    # 3 AM, 100% dark
#    - 8 PM - 8x Time Acceleration: 3    # 4 AM, 100% dark
#    - 9 PM - 8x Time Acceleration: 3    # 5 AM, 100% dark
#    - 10 PM - 8x Time Acceleration: 3    # 6 AM, 100% dark
#    - 11 PM - 8x Time Acceleration: 3    # 7 AM, 100% dark
season3:
  tracks:
    - Charlotte Motor Speedway: 10
    - Lime Rock Park: 10
    - Okayama International Circuit: 10
    - Oran Park Raceway: 10
    - Oulton Park Circuit: 10
    - Rudskogen Motorsenter: 10
    - Summit Point Raceway: 10
    - Tsukuba Circuit: 10
    - Virginia International Raceway: 10
    - Laguna Seca: 10
free:
  cars:
    - Cadillac CTS-V Racecar: 1
    - Formula Vee: 1
    - Global Mazda MX-5 Cup: 1
    - Kia Optima: 1
    - Lucas Oil Off Road Pro 2 Lite Truck: 1
    - Pontiac Solstice: 1
    - Radical SR8: 1
    - SCCA Spec Racer Ford: 1
    - Toyota GR86: 1
    - VW Beetle: 1
    - VW Jetta TDI Cup: 1
    - Legends: 1
    - Street Stock: 1
    - Legacy NASCAR Truck Chevrolet Silverado - 2008: 1
    - Ray FF1600: 1
  tracks:
    - Charlotte Motor Speedway: 1
    - Concord Speedway: 1
    - Langley Speedway: 1
    - Lanier National Speedway: 1
    - Limaland Motorsports Park: 1
    - Lime Rock Park: 1
    - Okayama International Circuit: 1
    - Oran Park Raceway: 1
    - Oulton Park Circuit: 1
    - Oxford Plains Speedway: 1
    - Rudskogen Motorsenter: 1
    - South Boston Speedway: 1
    - Summit Point Raceway: 1
    - Thompson Speedway Motorsports Park: 1
    - Tsukuba Circuit: 1
    - USA International Speedway: 1
    - Virginia International Raceway: 1
    - WeatherTech Raceway at Laguna Seca: 1

layouts:
  YOU MUST PICK A TRACK AS WELL:
    - Asshole.: 1
  VIR:
    - Full: 1
    - South: 1
    - North: 1
    - Grand: 1
  Tsukuba:
    - 2k Full: 1
    - 2k Moto: 1
  Summit:
    - Regular: 1
    - Short: 1
  Okayama:
    - Full: 1
    - Short: 1
  Oulton:
    - Intl: 1
    - Fosters: 1
    - Island: 1
    - Intl no Hislop: 1
    - Intl no Brittens: 1
    - Intl no Chicanes: 1
    - Fosters w Hislop: 1
    - Historic: 1
  Oran:
    - GP: 1
    - Moto: 1
    - South: 1
  Lime Rock:
    - GP: 1
    - Classic: 1
    - Chicanes: 1
    - West Bend: 1
  Charlotte:
    - Roval: 1
    - Roval 2018: 1
    - Roval Long 2018: 1
  Sonoma:
    - Cup: 1
    - Historic: 1
  Watkins Glen:
    - Cup: 1
    - Boot: 1
    - Classic Boot: 1
    - Classic: 1
date:
  month:
    - Jan: 1
    - Feb: 1
    - Mar: 1
    - Apr: 1
    - May: 1
    - Jun: 1
    - Jul: 1
    - Aug: 1
    - Sep: 1
    - Oct: 1
    - Nov: 1
    - Dec: 1
  day:
    - 1st: 1
    - 8th: 1
    - 15th: 1
    - 22nd: 1