# Define profiles here, which can be used by typing `/spin [profile_name]`
# A template below
#
# profile_name:
#   tracks:
#     - track_name: track_weight
#     ...
#   cars:
#     - car_name: car_weight
#     ...
season4:
  tracks: # Fair share weight = 24            # Max grid spots
    - Roval: 8                                # 60
    - Roval 2018: 8
    - Roval Long 2018: 8

#    - Lime Rock GP: 6                         # 60
#    - Lime Rock Classic: 6
#    - Lime Rock Chicanes: 6
#    - Lime Rock West Bend: 6

    - Okayama Full: 12                        # 62
    - Okayama Short: 12

    - Oran GP: 8                              # 57
    - Oran Moto: 8
    - Oran South: 8

#    - Oulton Intl: 3                          # 40
#    - Oulton Fosters: 3
#    - Oulton Island: 3
#    - Oulton Intl no Hislop: 3
#    - Oulton Intl no Brittens: 3
#    - Oulton Intl no Chicanes: 3
#    - Oulton Fosters w Hislop: 3
#    - Oulton Historic: 3

    - Rudskogen Motorsenter: 24               # 60

    - Summit Point Regular: 12                # 58
    - Summit Point Short: 12

    - Tsukuba 2k Full: 8                      # 60
    - Tsukuba 2k Moto: 8
    - Tsukuba 2k Short: 8

    - VIR Full: 6                             # 60
    - VIR South: 6
    - VIR North: 6
    - VIR Grand: 6

    - Laguna Seca: 24                         # 62

#    - Watkins Glen Cup: 6                     # 60
#    - Watkins Glen Boot: 6
#    - Watkins Glen Classic Boot: 6
#    - Watkins Glen Classic: 6
#
#    - Sonoma Cup: 12                          # 62
#    - Sonoma Cup Historic: 12

    - Montreal: 19       # target 80%         # 62

    - Phoenix Road: 19   # target 80%         # 51
conditions:
  starttime:
    - MIDNIGHT: 1
    - 1AM: 1
    - 2AM: 1
    - 3AM: 1
    - 4AM: 1
    - 5AM: 1
    - 6AM: 1
    - 7AM: 3
    - 8AM: 3
    - 9AM: 3
    - 10AM: 3
    - 11AM: 3
    - NOON: 3
    - 1PM: 3
    - 2PM: 3
    - 3PM: 3
    - 4PM: 3
    - 5PM: 3
    - 6PM: 3
    - 7PM: 1
    - 8PM: 1
    - 9PM: 1
    - 10PM: 1
    - 11PM: 1
  timeaccel:
    - 1x Time Acceleration: 1
    - 2x Time Acceleration: 1
    - 4x Time Acceleration: 1
    - 8x Time Acceleration: 1
season3:
  tracks:
    - Charlotte Motor Speedway: 10
    - Lime Rock Park: 10
    - Okayama International Circuit: 10
    - Oran Park Raceway: 10
    - Oulton Park Circuit: 10
    - Rudskogen Motorsenter: 10
    - Summit Point Raceway: 10
    - Tsukuba Circuit: 10
    - Virginia International Raceway: 10
    - Laguna Seca: 10
free:
  cars:
    - Cadillac CTS-V Racecar: 1
    - Formula Vee: 1
    - Global Mazda MX-5 Cup: 1
    - Kia Optima: 1
    - Lucas Oil Off Road Pro 2 Lite Truck: 1
    - Pontiac Solstice: 1
    - Radical SR8: 1
    - SCCA Spec Racer Ford: 1
    - Toyota GR86: 1
    - VW Beetle: 1
    - VW Jetta TDI Cup: 1
    - Legends: 1
    - Street Stock: 1
    - Legacy NASCAR Truck Chevrolet Silverado - 2008: 1
    - Ray FF1600: 1
  tracks:
    - Charlotte Motor Speedway: 1
    - Concord Speedway: 1
    - Langley Speedway: 1
    - Lanier National Speedway: 1
    - Limaland Motorsports Park: 1
    - Lime Rock Park: 1
    - Okayama International Circuit: 1
    - Oran Park Raceway: 1
    - Oulton Park Circuit: 1
    - Oxford Plains Speedway: 1
    - Rudskogen Motorsenter: 1
    - South Boston Speedway: 1
    - Summit Point Raceway: 1
    - Thompson Speedway Motorsports Park: 1
    - Tsukuba Circuit: 1
    - USA International Speedway: 1
    - Virginia International Raceway: 1
    - WeatherTech Raceway at Laguna Seca: 1

layouts:
  YOU MUST PICK A TRACK AS WELL:
    - Asshole.: 1
  VIR:
    - Full: 1
    - South: 1
    - North: 1
    - Grand: 1
  Tsukuba:
    - 2k Full: 1
    - 2k Moto: 1
  Summit:
    - Regular: 1
    - Short: 1
  Okayama:
    - Full: 1
    - Short: 1
  Oulton:
    - Intl: 1
    - Fosters: 1
    - Island: 1
    - Intl no Hislop: 1
    - Intl no Brittens: 1
    - Intl no Chicanes: 1
    - Fosters w Hislop: 1
    - Historic: 1
  Oran:
    - GP: 1
    - Moto: 1
    - South: 1
  Lime Rock:
    - GP: 1
    - Classic: 1
    - Chicanes: 1
    - West Bend: 1
  Charlotte:
    - Roval: 1
    - Roval 2018: 1
    - Roval Long 2018: 1
  Sonoma:
    - Cup: 1
    - Historic: 1
  Watkins Glen:
    - Cup: 1
    - Boot: 1
    - Classic Boot: 1
    - Classic: 1
date:
  month:
    - Jan: 1
    - Feb: 1
    - Mar: 1
    - Apr: 1
    - May: 1
    - Jun: 1
    - Jul: 1
    - Aug: 1
    - Sep: 1
    - Oct: 1
    - Nov: 1
    - Dec: 1
  day:
    - 1st: 1
    - 8th: 1
    - 15th: 1
    - 22nd: 1