# Define profiles here, which can be used by typing `/spin [profile_name]`
# A template below
#
# profile_name:
#   tracks:
#     track_name: track_weight
#     ...
#   cars:
#     car_name: car_weight
#     ...
default:
  tracks:
  - Oulton Park: 3
  - Lime Rock Park: 3
  - Tsukuba: 3
  - VIR: 3
  - Charlotte: 3
  - Phoenix: 2
  - Wild West: 1
  - Oran Park: 3
  - Rudskogen: 3
  - Summit Point: 3
  - Okayama: 3
  - Laguna Seca: 3
  - Daytona RX: 1
  cars:
    - Toyota GR86: 1
free:
  cars:
    - Cadillac CTS-V Racecar: 1
    - Formula Vee: 1
    - Global Mazda MX-5 Cup: 1
    - Kia Optima: 1
    - Lucas Oil Off Road Pro 2 Lite Truck: 1
    - Pontiac Solstice: 1
    - Radical SR8: 1
    - SCCA Spec Racer Ford: 1
    - Toyota GR86: 1
    - VW Beetle: 1
    - VW Jetta TDI Cup: 1
    - Legends: 1
    - Street Stock: 1
    - Legacy NASCAR Truck Chevrolet Silverado - 2008: 1
  tracks:
    - Charlotte Motor Speedway: 1
    - Concord Speedway: 1
    - Langley Speedway: 1
    - Lanier National Speedway: 1
    - Limaland Motorsports Park: 1
    - Lime Rock Park: 1
    - Okayama International Circuit: 1
    - Oran Park Raceway: 1
    - Oulton Park Circuit: 1
    - Oxford Plains Speedway: 1
    - Rudskogen Motorsenter: 1
    - South Boston Speedway: 1
    - Summit Point Raceway: 1
    - Thompson Speedway Motorsports Park: 1
    - Tsukuba Circuit: 1
    - USA International Speedway: 1
    - Virginia International Raceway: 1
    - WeatherTech Raceway at Laguna Seca: 1

layouts:
  Virginia International Raceway:
    - Full Course: 1
    - South: 1
    - North: 1
    - Patriot: 1
    - Grand West: 1
    - Grand East: 1
    - Patriot Reverse: 1
  Tsukuba Circuit:
    - 2000 Full: 1
    - 2000 Moto: 1
    - 2000 Short: 1
    - 1000 Full: 1
    - 1000 Outer: 1
    - 1000 Chicane: 1
    - 1000 Full Reverse: 1
  Summit Point Raceway:
    - Summit Point Raceway: 1
    - Jefferson Circuit: 1
    - Short: 1
    - Jefferson Reverse: 1
  Oulton Park Circuit:
    - International: 1
    - Fosters: 1
    - Island: 1
    - Intl w/out Hislop: 1
    - Intl w/out Brittens: 1
    - Intl w/no Chicanes: 1
    - Fosters w/ Hislop: 1
    - Island Historic: 1
  Oran Park Raceway:
    - Grand Prix: 1
    - South: 1
    - North: 1
    - North A: 1
    - North B: 1
    - Moto: 1
  Okayama International Circuit:
    - Full: 1
    - Short: 1
  Lime Rock Park:
    - Grand Prix: 1
    - Classic: 1
    - Chicanes: 1
    - West Bend Chicane: 1
  Charlotte Motor Speedway:
    - Roval: 1
    - Roval - 2018: 1
    - Roval Long - 2018: 1
    - Oval - 2018: 1
