# Define profiles here, which can be used by typing `/spin [profile_name]`
# A template below
#
# profile_name:
#   tracks:
#     track_name: track_weight
#     ...
#   cars:
#     car_name: car_weight
#     ...
default:
  tracks:
  - Oulton Park: 3
  - Lime Rock Park: 3
  - Tsukuba: 3
  - VIR: 3
  - Charlotte: 3
  - Phoenix: 2
  - Wild West: 1
  - Oran Park: 3
  - Rudskogen: 3
  - Summit Point: 3
  - Okayama: 3
  - Laguna Seca: 3
  - Daytona RX: 1
  cars:
    - Toyota GR86: 1
